---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol9_uln }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol9_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol9_uln | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol9_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol9_uln | bool }}"
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"


foreman_products_defaults_ol9_uln_olcne: &foreman_products_defaults_ol9_uln_olcne
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol9_uln_olcne }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol9_uln_olcne }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol9_uln_olcne | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol9_uln_olcne }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol9_uln_olcne | bool }}"


foreman_products_ol9_uln_olcne:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol9_uln_olcne }}"
    repositories:
      ### Oracle Linux 9 Cloud Native Environment - Oracle Linux 9 (x86_64) | ol9_x86_64_ocne ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 Cloud Native Environment - Oracle Linux 9 (x86_64)"
        description: Packages for components of Oracle Linux 9 Cloud Native Environment for Oracle Linux 9 (x86_64)
        label: "{{ foreman_repo_label_prefix | default('') }}ol9_x86_64_ocne"
        <<: *foreman_products_defaults_ol9_uln_olcne
        url: uln://ol9_x86_64_ocne
        organization: "{{ foreman_organization_ol9_uln_olcne }}"
      ### Oracle Linux 9 Cloud Native Environment 1.7 - Oracle Linux 9 (x86_64) | ol9_x86_64_olcne17 ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 Cloud Native Environment 1.7 - Oracle Linux 9 (x86_64)"
        description: Packages for components of the 1.7 release of Oracle Linux 9 Cloud Native Environment for Oracle Linux 9 (x86_64)
        label: "{{ foreman_repo_label_prefix | default('') }}ol9_uln_x86_64_olcne17"
        <<: *foreman_products_defaults_ol9_uln_olcne
        url: uln://ol9_x86_64_olcne17
        organization: "{{ foreman_organization_ol9_uln_olcne }}"
      ### Oracle Linux 9 Cloud Native Environment 1.8 - Oracle Linux 9 (x86_64) | ol9_x86_64_olcne18 ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 Cloud Native Environment 1.8 - Oracle Linux 9 (x86_64)"
        description: Packages for components of the 1.8 release of Oracle Linux 9 Cloud Native Environment for Oracle Linux 9 (x86_64)
        label: "{{ foreman_repo_label_prefix | default('') }}ol9_uln_x86_64_olcne18"
        <<: *foreman_products_defaults_ol9_uln_olcne
        url: uln://ol9_x86_64_olcne18
        organization: "{{ foreman_organization_ol9_uln_olcne }}"
      ### Oracle Linux 9 Cloud Native Environment 1.9 - Oracle Linux 9 (x86_64) | ol9_x86_64_olcne19 ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 Cloud Native Environment 1.9 - Oracle Linux 9 (x86_64)"
        description: Packages for components of the 1.9 release of Oracle Linux 9 Cloud Native Environment for Oracle Linux 9 (x86_64)
        label: "{{ foreman_repo_label_prefix | default('') }}ol9_uln_x86_64_olcne19"
        <<: *foreman_products_defaults_ol9_uln_olcne
        url: uln://ol9_x86_64_olcne19
        organization: "{{ foreman_organization_ol9_uln_olcne }}"


foreman_content_views_ol9_uln_olcne:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol9_uln_x86_64_ocne"
    organization: "{{ foreman_organization_ol9_uln_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 Cloud Native Environment - Oracle Linux 9 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol9_uln_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol9_uln_x86_64_olcne17"
    organization: "{{ foreman_organization_ol9_uln_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 Cloud Native Environment 1.7 - Oracle Linux 9 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol9_uln_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol9_uln_x86_64_olcne18"
    organization: "{{ foreman_organization_ol9_uln_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 Cloud Native Environment 1.8 - Oracle Linux 9 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol9_uln_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol9_uln_x86_64_olcne19"
    organization: "{{ foreman_organization_ol9_uln_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 Cloud Native Environment 1.9 - Oracle Linux 9 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol9_uln_olcne }}"

