---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln | bool }}"
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"


foreman_products_defaults_ol9_uln_oci: &foreman_products_defaults_ol9_uln_oci
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol9_uln_oci }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol9_uln_oci }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol9_uln_oci | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol9_uln_oci }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol9_uln_oci | bool }}"


foreman_products_ol9_uln_oci:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol9_uln_oci }}"
    repositories:
      ### Oracle Linux 9 OCI Included Packages (x86_64) | ol9_x86_64_oci_included ###
      - name: Oracle Linux 9 OCI Included Packages (x86_64)
        description: Oracle Linux 9 packages specifically for use in Oracle Cloud Infrastructure (x86_64)
        label: ol9_uln_x86_64_oci_included
        url: uln://ol9_x86_64_oci_included
        <<: *foreman_products_defaults_ol9_uln_oci
        organization: "{{ foreman_organization_ol9_uln_oci }}"


foreman_content_views_ol9_uln_oci:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol9_uln_x86_64_oci_included"
    organization: "{{ foreman_organization_ol9_uln_oci }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 OCI Included Packages (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol9_uln_oci }}"

