---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7 | bool }}"


foreman_products_defaults_ol7_mysql: &foreman_products_defaults_ol7_mysql
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_mysql }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_mysql }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_mysql | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_mysql }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_mysql | bool }}"


foreman_products_ol7_mysql55:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_mysql55 }}"
    repositories:
      ### MySQL 5.5 for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL55_community ###
      - name: MySQL 5.5 for Oracle Linux 7 (x86_64)
        description: Latest MySQL 5.5 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL55_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL55/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql55 }}"

foreman_products_ol7_mysql56:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_mysql56 }}"
    repositories:
      ### MySQL 5.6 for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL56_community ###
      - name: MySQL 5.6 for Oracle Linux 7 (x86_64)
        description: Latest MySQL 5.6 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL56_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL56/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql56 }}"

foreman_products_ol7_mysql57:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_mysql57 }}"
    repositories:
      ### MySQL 5.7 for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL57_community ###
      - name: MySQL 5.7 for Oracle Linux 7 (x86_64)
        description: Latest MySQL 5.7 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL57_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL57_community/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql57 }}"

foreman_products_ol7_mysql80:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_mysql80 }}"
    repositories:
      ### MySQL 8.0 Connectors Community for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL80_connectors_community ###
      - name: MySQL 8.0 Connectors Community for Oracle Linux 7 (x86_64)
        description: Latest MySQL 8.0 Connectors Community packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL80_connectors_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL80/connectors/community/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql80 }}"
      ### MySQL 8.0 for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL80_community ###
      - name: MySQL 8.0 for Oracle Linux 7 (x86_64)
        description: Latest MySQL 8.0 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL80_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL80_community/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql80 }}"
      ### MySQL 8.0 Tools Community for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL80_tools_community ###
      - name: MySQL 8.0 Tools Community for Oracle Linux 7 (x86_64)
        description: Latest MySQL 8.0 Tools Community packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL80_tools_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL80/tools/community/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql80 }}"

foreman_products_ol7_mysql84:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_mysql84 }}"
    repositories:
      ### MySQL 8.4 for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL84_community ###
      - name: MySQL 8.4 for Oracle Linux 7 (x86_64)
        description: Latest MySQL 8.4 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL84_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL84_community/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql84 }}"
      ### MySQL 8.4 Tools Community for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL84_tools_community ###
      - name: MySQL 8.4 Tools Community for Oracle Linux 7 (x86_64)
        description: Latest MySQL 8.4 Tools Community packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL84_tools_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL84/tools/community/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql84 }}"

foreman_products_ol7_mysql_main:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_mysql80 }}"
    repositories:
      ### MySQL Connectors Community for Oracle Linux 7 (x86_64) | ol7_x86_64_MySQL_connectors_community ###
      - name: MySQL Connectors Community for Oracle Linux 7 (x86_64)
        description: Latest MySQL Connectors Community packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_MySQL_connectors_community
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/MySQL/connectors/community/x86_64/"
        <<: *foreman_products_defaults_ol7_mysql
        organization: "{{ foreman_organization_ol7_mysql }}"

foreman_products_ol7_mysql: "{{ ( foreman_products_ol7_mysql_main | default([]) if foreman_enable_ol7_mysql else [] ) |
  union( foreman_products_ol7_mysql55 | default([]) if foreman_enable_ol7_mysql55 else [] ) |
  union( foreman_products_ol7_mysql56 | default([]) if foreman_enable_ol7_mysql56 else [] ) |
  union( foreman_products_ol7_mysql57 | default([]) if foreman_enable_ol7_mysql57 else [] ) |
  union( foreman_products_ol7_mysql80 | default([]) if foreman_enable_ol7_mysql80 else [] ) |
  union( foreman_products_ol7_mysql84 | default([]) if foreman_enable_ol7_mysql84 else [] )
  }}"


foreman_content_views_ol7_mysql55:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL55_community"
    organization: "{{ foreman_organization_ol7_mysql55 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 5.5 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql55 }}"

foreman_content_views_ol7_mysql56:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL56_community"
    organization: "{{ foreman_organization_ol7_mysql56 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 5.6 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql56 }}"

foreman_content_views_ol7_mysql57:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL57_community"
    organization: "{{ foreman_organization_ol7_mysql57 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 5.7 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql57 }}"

foreman_content_views_ol7_mysql80:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL80_connectors_community"
    organization: "{{ foreman_organization_ol7_mysql80 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 8.0 Connectors Community for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql80 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL80_community"
    organization: "{{ foreman_organization_ol7_mysql80 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 8.0 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql80 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL80_tools_community"
    organization: "{{ foreman_organization_ol7_mysql80 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 8.0 Tools Community for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql80 }}"

foreman_content_views_ol7_mysql84:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL84_community"
    organization: "{{ foreman_organization_ol7_mysql84 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 8.4 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql84 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL84_tools_community"
    organization: "{{ foreman_organization_ol7_mysql84 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 8.4 Tools Community for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql84 }}"

foreman_content_views_ol7_mysql_main:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_MySQL_connectors_community"
    organization: "{{ foreman_organization_ol7_mysql }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL Connectors Community for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_mysql }}"

foreman_content_views_ol7_mysql: "{{ ( foreman_content_views_ol7_mysql_main | default([]) if foreman_enable_ol7_mysql else [] ) |
  union( foreman_content_views_ol7_mysql55 | default([]) if foreman_enable_ol7_mysql55 else [] ) |
  union( foreman_content_views_ol7_mysql56 | default([]) if foreman_enable_ol7_mysql56 else [] ) |
  union( foreman_content_views_ol7_mysql57 | default([]) if foreman_enable_ol7_mysql57 else [] ) |
  union( foreman_content_views_ol7_mysql80 | default([]) if foreman_enable_ol7_mysql80 else [] ) |
  union( foreman_content_views_ol7_mysql84 | default([]) if foreman_enable_ol7_mysql84 else [] )
  }}"

