---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln | bool }}"
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"


foreman_products_defaults_ol8_uln_am: &foreman_products_defaults_ol8_uln_am
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol8_uln_am }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol8_uln_am }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol8_uln_am | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol8_uln_am }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol8_uln_am | bool }}"


foreman_products_ol8_uln_am10:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol8_uln_am10 }}"
    repositories:
      ### Oracle Linux Automation Manager 1.0, based on the open source projects Ansible and AWX | ol8_x86_64_automation ###
      - name: Oracle Linux Automation Manager 1.0, based on the open source projects Ansible and AWX
        description: Oracle Linux Automation Manager 1.0, based on the open source projects Ansible and AWX.
        label: ol8_uln_x86_64_automation
        url: uln://ol8_x86_64_automation
        <<: *foreman_products_defaults_ol8_uln_am
        organization: "{{ foreman_organization_ol8_uln_am10 }}"

foreman_products_ol8_uln_am20:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol8_uln_am20 }}"
    repositories:
      ### Oracle Linux Automation Manager 2.0, based on the open source projects Ansible and AWX | ol8_x86_64_automation2 ###
      - name: Oracle Linux Automation Manager 2.0, based on the open source projects Ansible and AWX
        description: Oracle Linux Automation Manager 2.0, based on the open source projects Ansible and AWX.
        label: ol8_uln_x86_64_automation2
        url: uln://ol8_x86_64_automation2
        <<: *foreman_products_defaults_ol8_uln_am
        organization: "{{ foreman_organization_ol8_uln_am20 }}"

foreman_products_ol8_uln_am: "{{ [] |
  union( foreman_products_ol8_uln_am10 | default([]) if foreman_enable_ol8_uln_am10 else [] ) |
  union( foreman_products_ol8_uln_am20 | default([]) if foreman_enable_ol8_uln_am20 else [] )
  }}"


foreman_content_views_ol8_uln_am10:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_uln_x86_64_automation"
    organization: "{{ foreman_organization_ol8_uln_am10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Automation Manager 1.0, based on the open source projects Ansible and AWX"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_uln_am10 }}"

foreman_content_views_ol8_uln_am20:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_uln_x86_64_automation2"
    organization: "{{ foreman_organization_ol8_uln_am20 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Automation Manager 2.0, based on the open source projects Ansible and AWX"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_uln_am20 }}"

foreman_content_views_ol8_uln_am: "{{ [] |
  union( foreman_content_views_ol8_uln_am10 | default([]) if foreman_enable_ol8_uln_am10 else [] ) |
  union( foreman_content_views_ol8_uln_am20 | default([]) if foreman_enable_ol8_uln_am20 else [] )
  }}"

