---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln | bool }}"
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"


foreman_products_defaults_ol7_uln_olm: &foreman_products_defaults_ol7_uln_olm
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln_olm }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln_olm }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln_olm | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln_olm }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln_olm | bool }}"


foreman_products_ol7_uln_olm_spacewalk26:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"
    repositories:
      ### Spacewalk Client 2.6 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk26_client ###
      - name: Spacewalk Client 2.6 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.6 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk26_client
        url: uln://ol7_x86_64_spacewalk26_client
        <<: *foreman_products_defaults_ol7_uln_olm
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"
      ### Spacewalk Server 2.6 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk26_server ###
      - name: Spacewalk Server 2.6 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.6 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk26_server
        url: uln://ol7_x86_64_spacewalk26_server
        <<: *foreman_products_defaults_ol7_uln_olm
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"

foreman_products_ol7_uln_olm_spacewalk27:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"
    repositories:
      ### Spacewalk Client 2.7 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk27_client ###
      - name: Spacewalk Client 2.7 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.7 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk27_client
        url: uln://ol7_x86_64_spacewalk27_client
        <<: *foreman_products_defaults_ol7_uln_olm
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"
      ### Spacewalk Server 2.7 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk27_server ###
      - name: Spacewalk Server 2.7 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.7 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk27_server
        url: uln://ol7_x86_64_spacewalk27_server
        <<: *foreman_products_defaults_ol7_uln_olm
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"

foreman_products_ol7_uln_olm_spacewalk210:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"
    repositories:
      ### Spacewalk Client 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk210_client ###
      - name: Spacewalk Client 2.10 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk210_client
        url: uln://ol7_x86_64_spacewalk210_client
        <<: *foreman_products_defaults_ol7_uln_olm
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"
      ### Spacewalk Server 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk210_server ###
      - name: Spacewalk Server 2.10 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk210_server
        url: uln://ol7_x86_64_spacewalk210_server
        <<: *foreman_products_defaults_ol7_uln_olm
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"

foreman_products_ol7_uln_olm_oraclelinuxmanager210:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"
    repositories:
      ### Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_oraclelinuxmanager210_client ###
      - name: Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64)
        description: All Oracle Linux Manager (formerly Spacewalk) Client 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_oraclelinuxmanager210_client
        url: uln://ol7_x86_64_oraclelinuxmanager210_client
        <<: *foreman_products_defaults_ol7_uln_olm
        organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"
      ### Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_oraclelinuxmanager210_server ###
      - name: Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64)
        description: All Oracle Linux Manager (formerly Spacewalk) Server 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_oraclelinuxmanager210_server
        url: uln://ol7_x86_64_oraclelinuxmanager210_server
        <<: *foreman_products_defaults_ol7_uln_olm
        organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"

foreman_products_ol7_uln_olm: "{{ [] |
  union( foreman_products_ol7_uln_olm_spacewalk26 | default([]) if foreman_enable_ol7_uln_olm_spacewalk26 else [] ) |
  union( foreman_products_ol7_uln_olm_spacewalk27 | default([]) if foreman_enable_ol7_uln_olm_spacewalk27 else [] ) |
  union( foreman_products_ol7_uln_olm_spacewalk210 | default([]) if foreman_enable_ol7_uln_olm_spacewalk210 else [] ) |
  union( foreman_products_ol7_uln_olm_oraclelinuxmanager210 | default([]) if foreman_enable_ol7_uln_olm_oraclelinuxmanager210 else [] )
  }}"


foreman_content_views_ol7_uln_olm_spacewalk26:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_spacewalk26_client"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Spacewalk Client 2.6 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_olm_spacewalk26 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_spacewalk26_server"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Spacewalk Server 2.6 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_olm_spacewalk26 }}"

foreman_content_views_ol7_uln_olm_spacewalk27:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_spacewalk27_client"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Spacewalk Client 2.7 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_olm_spacewalk27 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_spacewalk27_server"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Spacewalk Server 2.7 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_olm_spacewalk27 }}"

foreman_content_views_ol7_uln_olm_spacewalk210:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_spacewalk210_client"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Spacewalk Client 2.10 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_olm_spacewalk210 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_spacewalk210_server"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Spacewalk Server 2.10 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_olm_spacewalk210 }}"

foreman_content_views_ol7_uln_olm_oraclelinuxmanager210:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_oraclelinuxmanager210_client"
    organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_olm_oraclelinuxmanager210 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_oraclelinuxmanager210_server"
    organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_olm_oraclelinuxmanager210 }}"

foreman_content_views_ol7_uln_olm: "{{ [] |
  union( foreman_content_views_ol7_uln_olm_spacewalk26 | default([]) if foreman_enable_ol7_uln_olm_spacewalk26 else [] ) |
  union( foreman_content_views_ol7_uln_olm_spacewalk27 | default([]) if foreman_enable_ol7_uln_olm_spacewalk27 else [] ) |
  union( foreman_content_views_ol7_uln_olm_spacewalk210 | default([]) if foreman_enable_ol7_uln_olm_spacewalk210 else [] ) |
  union( foreman_content_views_ol7_uln_olm_oraclelinuxmanager210 | default([]) if foreman_enable_ol7_uln_olm_oraclelinuxmanager210 else [] )
  }}"

