---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol9_uln }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol9_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol9_uln | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol9_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol9_uln | bool }}"
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"


foreman_products_defaults_ol9_uln_virtualization: &foreman_products_defaults_ol9_uln_virtualization
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol9_uln_virtualization }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol9_uln_virtualization }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol9_uln_virtualization | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol9_uln_virtualization }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol9_uln_virtualization | bool }}"


foreman_products_ol9_uln_virtualization_kvm_utils:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol9_uln_virtualization_kvm_utils }}"
    repositories:
      ### Oracle Linux 9 KVM Utilities (x86_64) | ol9_x86_64_kvm_utils ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 KVM Utilities (x86_64)"
        description: Latest Oracle Linux 9 KVM Utilities Packages (x86_64)
        label: "{{ foreman_repo_label_prefix | default('') }}ol9_uln_x86_64_kvm_utils"
        <<: *foreman_products_defaults_ol9_uln_virtualization
        url: uln://ol9_x86_64_kvm_utils
        organization: "{{ foreman_organization_ol9_uln_virtualization_kvm_utils }}"
      ### Developer Preview of KVM Utilities for Oracle Linux 9 (x86_64) | ol9_x86_64_developer_kvm_utils ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Developer Preview of KVM Utilities for Oracle Linux 9 (x86_64)"
        description: Latest KVM Utility packages for test and development for Oracle Linux 9 (x86_64).
        label: "{{ foreman_repo_label_prefix | default('') }}ol9_uln_x86_64_developer_kvm_utils"
        <<: *foreman_products_defaults
        url: uln://ol9_x86_64_developer_kvm_utils
        organization: "{{ foreman_organization_ol9_uln_virtualization_kvm_utils }}"

foreman_products_ol9_uln_virtualization: "{{ [] |
  union( foreman_products_ol9_uln_virtualization_kvm_utils | default([]) if foreman_enable_ol9_uln_virtualization_kvm_utils else [] )
  }}"


foreman_content_views_ol9_uln_virtualization_kvm_utils:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol9_uln_x86_64_kvm_utils"
    organization: "{{ foreman_organization_ol9_uln_virtualization_kvm_utils }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 9 KVM Utilities (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol9_uln_virtualization_kvm_utils }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol9_uln_x86_64_developer_kvm_utils"
    organization: "{{ foreman_organization_ol9_uln_virtualization_kvm_utils }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Developer Preview of KVM Utilities for Oracle Linux 9 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol9_uln_virtualization_kvm_utils }}"

foreman_content_views_ol9_uln_virtualization: "{{ [] |
  union( foreman_content_views_ol9_uln_virtualization_kvm_utils | default([]) if foreman_enable_ol9_uln_virtualization_kvm_utils else [] )
  }}"

