---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7 | bool }}"


foreman_products_defaults_ol9_olcne: &foreman_products_defaults_ol9_olcne
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol9_olcne }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol9_olcne }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol9_olcne | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol9_olcne }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol9_olcne | bool }}"


foreman_products_ol9_olcne: []


foreman_content_views_ol9_olcne: []

