---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7 | bool }}"


foreman_products_defaults_ol7_storage: &foreman_products_defaults_ol7_storage
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_storage }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_storage }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_storage | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_storage }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_storage | bool }}"


foreman_products_ol7_storage_ceph10:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_storage_ceph10 }}"
    repositories:
      ### Ceph Storage for Oracle Linux Release 1.0 (Oracle Linux 7.1 and later) | ol7_x86_64_ceph10 ###
      - name: Ceph Storage for Oracle Linux Release 1.0 (Oracle Linux 7.1 and later)
        description: Latest packages for Ceph Storage for Oracle Linux Release 1.0 (Oracle Linux 7.1 and later).
        label: ol7_x86_64_ceph10
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/ceph10/x86_64/"
        <<: *foreman_products_defaults_ol7_storage
        organization: "{{ foreman_organization_ol7_storage_ceph10 }}"

foreman_products_ol7_storage_ceph20:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_storage_ceph20 }}"
    repositories:
      ### Ceph Storage for Oracle Linux Release 2.0 (Oracle Linux 7.2 and later) | ol7_x86_64_ceph ###
      - name: Ceph Storage for Oracle Linux Release 2.0 (Oracle Linux 7.2 and later)
        description: Latest packages for Ceph Storage for Oracle Linux Release 2.0 (Oracle Linux 7.2 and later).
        label: ol7_x86_64_ceph
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/ceph/x86_64/"
        <<: *foreman_products_defaults_ol7_storage
        organization: "{{ foreman_organization_ol7_storage_ceph20 }}"

foreman_products_ol7_storage_ceph30:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_storage_ceph30 }}"
    repositories:
      ### Ceph Storage for Oracle Linux Release 3.0 (Oracle Linux 7.5 and later) | ol7_x86_64_ceph30 ###
      - name: Ceph Storage for Oracle Linux Release 3.0 (Oracle Linux 7.5 and later)
        description: Latest packages for Ceph Storage for Oracle Linux Release 3.0 (Oracle Linux 7.5 and later).
        label: ol7_x86_64_ceph30
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/ceph30/x86_64/"
        <<: *foreman_products_defaults_ol7_storage
        organization: "{{ foreman_organization_ol7_storage_ceph30 }}"

foreman_products_ol7_storage_gluster312:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_storage_gluster312 }}"
    repositories:
      ### Glusterfs 3.12 for Oracle Linux 7 (x86_64) | ol7_x86_64_gluster312 ###
      - name: Glusterfs 3.12 for Oracle Linux 7 (x86_64)
        description: Latest GlusterFs 3.12 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_gluster312
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/gluster312/x86_64/"
        <<: *foreman_products_defaults_ol7_storage
        organization: "{{ foreman_organization_ol7_storage_gluster312 }}"

foreman_products_ol7_storage_gluster41:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_storage_gluster41 }}"
    repositories:
      ### Glusterfs 4.1 for Oracle Linux 7 (x86_64) | ol7_x86_64_gluster41 ###
      - name: Glusterfs 4.1 for Oracle Linux 7 (x86_64)
        description: Latest GlusterFs 4.1 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_gluster41
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/gluster41/x86_64/"
        <<: *foreman_products_defaults_ol7_storage
        organization: "{{ foreman_organization_ol7_storage_gluster41 }}"

foreman_products_ol7_storage_gluster5:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_storage_gluster5 }}"
    repositories:
      ### Gluster 5 for Oracle Linux 7 (x86_64) | ol7_x86_64_gluster5 ###
      - name: Gluster 5 for Oracle Linux 7 (x86_64)
        description: Latest Gluster 5 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_gluster5
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/gluster5/x86_64/"
        <<: *foreman_products_defaults_ol7_storage
        organization: "{{ foreman_organization_ol7_storage_gluster5 }}"

foreman_products_ol7_storage_gluster6:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_storage_gluster6 }}"
    repositories:
      ### Gluster 6 for Oracle Linux 7 (x86_64) | ol7_x86_64_gluster6 ###
      - name: Gluster 6 for Oracle Linux 7 (x86_64)
        description: Latest Gluster 6 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_gluster6
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/gluster6/x86_64/"
        <<: *foreman_products_defaults_ol7_storage
        organization: "{{ foreman_organization_ol7_storage_gluster6 }}"

foreman_products_ol7_storage_gluster8:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_storage_gluster8 }}"
    repositories:
      ### Gluster 8 for Oracle Linux 7 (x86_64) | ol7_x86_64_gluster8 ###
      - name: Gluster 8 for Oracle Linux 7 (x86_64)
        description: Latest Gluster 8 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_gluster8
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/gluster8/x86_64/"
        <<: *foreman_products_defaults_ol7_storage
        organization: "{{ foreman_organization_ol7_storage_gluster8 }}"

foreman_products_ol7_storage: "{{ [] |
  union( foreman_products_ol7_storage_ceph10 | default([]) if foreman_enable_ol7_storage_ceph10 else [] ) |
  union( foreman_products_ol7_storage_ceph20 | default([]) if foreman_enable_ol7_storage_ceph20 else [] ) |
  union( foreman_products_ol7_storage_ceph30 | default([]) if foreman_enable_ol7_storage_ceph30 else [] ) |
  union( foreman_products_ol7_storage_gluster312 | default([]) if foreman_enable_ol7_storage_gluster312 else [] ) |
  union( foreman_products_ol7_storage_gluster41 | default([]) if foreman_enable_ol7_storage_gluster41 else [] ) |
  union( foreman_products_ol7_storage_gluster5 | default([]) if foreman_enable_ol7_storage_gluster5 else [] ) |
  union( foreman_products_ol7_storage_gluster6 | default([]) if foreman_enable_ol7_storage_gluster6 else [] ) |
  union( foreman_products_ol7_storage_gluster8 | default([]) if foreman_enable_ol7_storage_gluster8 else [] )
  }}"


foreman_content_views_ol7_storage_ceph10:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_ceph10"
    organization: "{{ foreman_organization_ol7_storage_ceph10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph Storage for Oracle Linux Release 1.0 (Oracle Linux 7.1 and later)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_storage_ceph10 }}"

foreman_content_views_ol7_storage_ceph20:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_ceph"
    organization: "{{ foreman_organization_ol7_storage_ceph20 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph Storage for Oracle Linux Release 2.0 (Oracle Linux 7.2 and later)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_storage_ceph20 }}"

foreman_content_views_ol7_storage_ceph30:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_ceph30"
    organization: "{{ foreman_organization_ol7_storage_ceph30 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph Storage for Oracle Linux Release 3.0 (Oracle Linux 7.5 and later)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_storage_ceph30 }}"

foreman_content_views_ol7_storage_gluster312:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_gluster312"
    organization: "{{ foreman_organization_ol7_storage_gluster312 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Glusterfs 3.12 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_storage_gluster312 }}"

foreman_content_views_ol7_storage_gluster41:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_gluster41"
    organization: "{{ foreman_organization_ol7_storage_gluster41 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Glusterfs 4.1 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_storage_gluster41 }}"

foreman_content_views_ol7_storage_gluster5:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_gluster5"
    organization: "{{ foreman_organization_ol7_storage_gluster5 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Gluster 5 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_storage_gluster5 }}"

foreman_content_views_ol7_storage_gluster6:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_gluster6"
    organization: "{{ foreman_organization_ol7_storage_gluster6 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Gluster 6 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_storage_gluster6 }}"

foreman_content_views_ol7_storage_gluster8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_gluster8"
    organization: "{{ foreman_organization_ol7_storage_gluster8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Gluster 8 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_storage_gluster8 }}"

foreman_content_views_ol7_storage: "{{ [] |
  union( foreman_content_views_ol7_storage_ceph10 | default([]) if foreman_enable_ol7_storage_ceph10 else [] ) |
  union( foreman_content_views_ol7_storage_ceph20 | default([]) if foreman_enable_ol7_storage_ceph20 else [] ) |
  union( foreman_content_views_ol7_storage_ceph30 | default([]) if foreman_enable_ol7_storage_ceph30 else [] ) |
  union( foreman_content_views_ol7_storage_gluster312 | default([]) if foreman_enable_ol7_storage_gluster312 else [] ) |
  union( foreman_content_views_ol7_storage_gluster41 | default([]) if foreman_enable_ol7_storage_gluster41 else [] ) |
  union( foreman_content_views_ol7_storage_gluster5 | default([]) if foreman_enable_ol7_storage_gluster5 else [] ) |
  union( foreman_content_views_ol7_storage_gluster6 | default([]) if foreman_enable_ol7_storage_gluster6 else [] ) |
  union( foreman_content_views_ol7_storage_gluster8 | default([]) if foreman_enable_ol7_storage_gluster8 else [] )
  }}"

