---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7 | bool }}"


foreman_products_defaults_ol8_storage: &foreman_products_defaults_ol8_storage
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol8_storage }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol8_storage }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol8_storage | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol8_storage }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol8_storage | bool }}"


foreman_products_ol8_storage:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol8_storage }}"
    repositories:
      ### Oracle Linux 8 (x86_64) Gluster AppStream | ol8_x86_64_gluster_appstream ###
      - name: Oracle Linux 8 (x86_64) Gluster AppStream
        description: Appstream Gluster packages for Oracle Linux 8 (x86_64)
        label: ol8_x86_64_gluster_appstream
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/gluster/appstream/x86_64/"
        <<: *foreman_products_defaults_ol8_storage
        organization: "{{ foreman_organization_ol8_storage }}"


foreman_content_views_ol8_storage:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_x86_64_gluster_appstream"
    organization: "{{ foreman_organization_ol8_storage }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 8 (x86_64) Gluster AppStream"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_storage }}"

