---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7 | bool }}"


foreman_products_defaults_ol8_virtualization: &foreman_products_defaults_ol8_virtualization
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol8_virtualization }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol8_virtualization }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol8_virtualization | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol8_virtualization }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol8_virtualization | bool }}"


foreman_products_ol8_virtualization_kvm_utils:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol8_virtualization_kvm_utils }}"
    repositories:
      ### Oracle Linux 8 KVM Application Stream (x86_64) | ol8_x86_64_kvm_appstream ###
      - name: Oracle Linux 8 KVM Application Stream (x86_64)
        description: Latest KVM Application Stream Packages for Oracle Linux 8 (x86_64)
        label: ol8_x86_64_kvm_appstream
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/kvm/appstream/x86_64/"
        <<: *foreman_products_defaults_ol8_virtualization
        organization: "{{ foreman_organization_ol8_virtualization_kvm_utils }}"

foreman_products_ol8_virtualization_ovirt44:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol8_virtualization_ovirt44 }}"
    repositories:
      ### oVirt Release 4.4 on Oracle Linux 8 (x86_64) | ol8_x86_64_ovirt44 ###
      - name: oVirt Release 4.4 on Oracle Linux 8 (x86_64)
        description: Latest packages for oVirt Release 4.4 on Oracle Linux 8 (x86_64).
        label: ol8_x86_64_ovirt44
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/ovirt44/x86_64/"
        <<: *foreman_products_defaults_ol8_virtualization
        organization: "{{ foreman_organization_ol8_virtualization_ovirt44 }}"
      ### oVirt Release 4.4 on Oracle Linux 8 (x86_64) - Extra | ol8_x86_64_ovirt44_extras ###
      - name: oVirt Release 4.4 on Oracle Linux 8 (x86_64) - Extra
        description: Latest extra packages for oVirt Release 4.4 on Oracle Linux 8 (x86_64).
        label: ol8_x86_64_ovirt44_extras
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/ovirt44/extras/x86_64/"
        <<: *foreman_products_defaults_ol8_virtualization
        organization: "{{ foreman_organization_ol8_virtualization_ovirt44 }}"

foreman_products_ol8_virtualization: "{{ [] |
  union( foreman_products_ol8_virtualization_kvm_utils | default([]) if foreman_enable_ol8_virtualization_kvm_utils else [] ) |
  union( foreman_products_ol8_virtualization_ovirt44 | default([]) if foreman_enable_ol8_virtualization_ovirt44 else [] )
  }}"


foreman_content_views_ol8_virtualization_kvm_utils:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_x86_64_kvm_appstream"
    organization: "{{ foreman_organization_ol8_virtualization_kvm_utils }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux 8 KVM Application Stream (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_virtualization_kvm_utils }}"

foreman_content_views_ol8_virtualization_ovirt44:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_x86_64_ovirt44"
    organization: "{{ foreman_organization_ol8_virtualization_ovirt44 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}oVirt Release 4.4 on Oracle Linux 8 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_virtualization_ovirt44 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_x86_64_ovirt44_extras"
    organization: "{{ foreman_organization_ol8_virtualization_ovirt44 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}oVirt Release 4.4 on Oracle Linux 8 (x86_64) - Extra"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_virtualization_ovirt44 }}"

foreman_content_views_ol8_virtualization: "{{ [] |
  union( foreman_content_views_ol8_virtualization_kvm_utils | default([]) if foreman_enable_ol8_virtualization_kvm_utils else [] ) |
  union( foreman_content_views_ol8_virtualization_ovirt44 | default([]) if foreman_enable_ol8_virtualization_ovirt44 else [] )
  }}"

