---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7 | bool }}"


foreman_products_defaults_ol8_olm: &foreman_products_defaults_ol8_olm
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol8_olm }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol8_olm }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol8_olm | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol8_olm }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol8_olm | bool }}"


foreman_products_ol8_olm:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol8_olm }}"
    repositories:
      ### Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 8 (x86_64) | ol8_x86_64_oraclelinuxmanager210_client ###
      - name: Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 8 (x86_64)
        description: All Oracle Linux Manager (formerly Spacewalk) Client 2.10 packages released for Oracle Linux 8 (x86_64).
        label: ol8_x86_64_oraclelinuxmanager210_client
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/oraclelinuxmanager210/client/x86_64/"
        <<: *foreman_products_defaults_ol8_olm
        organization: "{{ foreman_organization_ol8_olm }}"


foreman_content_views_ol8_olm:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_x86_64_oraclelinuxmanager210_client"
    organization: "{{ foreman_organization_ol8_olm }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 8 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_olm }}"

