---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln | bool }}"
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"


foreman_products_defaults_ol7_uln_ksplice: &foreman_products_defaults_ol7_uln_ksplice
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln_ksplice }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln_ksplice }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln_ksplice | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln_ksplice }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln_ksplice | bool }}"


foreman_products_ol7_uln_ksplice:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_ksplice }}"
    repositories:
      ### Ksplice for Oracle Linux 7 (x86_64) | ol7_x86_64_ksplice ###
      - name: Ksplice for Oracle Linux 7 (x86_64)
        description: Oracle Ksplice clients, updates, and dependencies for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_ksplice
        url: uln://ol7_x86_64_ksplice
        <<: *foreman_products_defaults_ol7_uln_ksplice
        organization: "{{ foreman_organization_ol7_uln_ksplice }}"
      ### Ksplice aware userspace packages for Oracle Linux 7 (x86_64) | ol7_x86_64_userspace_ksplice ###
      - name: Ksplice aware userspace packages for Oracle Linux 7 (x86_64)
        description: Latest packages for Ksplice aware userspace packages for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_userspace_ksplice
        url: uln://ol7_x86_64_userspace_ksplice
        <<: *foreman_products_defaults_ol7_uln_ksplice
        organization: "{{ foreman_organization_ol7_uln_ksplice }}"


foreman_content_views_ol7_uln_ksplice:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_ksplice"
    organization: "{{ foreman_organization_ol7_uln_ksplice }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ksplice for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_ksplice }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_userspace_ksplice"
    organization: "{{ foreman_organization_ol7_uln_ksplice }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ksplice aware userspace packages for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_ksplice }}"

