---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7 | bool }}"


foreman_products_defaults_ol8_mysql: &foreman_products_defaults_ol8_mysql
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol8_mysql }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol8_mysql }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol8_mysql | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol8_mysql }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol8_mysql | bool }}"


foreman_products_ol8_mysql:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol8_mysql }}"
    repositories:
      ### MySQL 8.0 Connectors Community for Oracle Linux 8 (x86_64) | ol8_x86_64_MySQL80_connectors_community ###
      - name: MySQL 8.0 Connectors Community for Oracle Linux 8 (x86_64)
        description: Latest MySQL 8.0 Connectors Community packages for Oracle Linux 8 (x86_64).
        label: ol8_x86_64_MySQL80_connectors_community
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/MySQL80/connectors/community/x86_64/"
        <<: *foreman_products_defaults_ol8_mysql
        organization: "{{ foreman_organization_ol8_mysql }}"
      ### MySQL 8.0 for Oracle Linux 8 (x86_64) | ol8_x86_64_MySQL80_community ###
      - name: MySQL 8.0 for Oracle Linux 8 (x86_64)
        description: Latest MySQL 8.0 packages for Oracle Linux 8 (x86_64).
        label: ol8_x86_64_MySQL80_community
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/MySQL80/community/x86_64/"
        <<: *foreman_products_defaults_ol8_mysql
        organization: "{{ foreman_organization_ol8_mysql }}"
      ### MySQL 8.0 Tools Community for Oracle Linux 8 (x86_64) | ol8_x86_64_MySQL80_tools_community ###
      - name: MySQL 8.0 Tools Community for Oracle Linux 8 (x86_64)
        description: Latest MySQL 8.0 Tools Community packages for Oracle Linux 8 (x86_64).
        label: ol8_x86_64_MySQL80_tools_community
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/MySQL80/tools/community/x86_64/"
        <<: *foreman_products_defaults_ol8_mysql
        organization: "{{ foreman_organization_ol8_mysql }}"


foreman_content_views_ol8_mysql:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_x86_64_MySQL80_connectors_community"
    organization: "{{ foreman_organization_ol8_mysql }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 8.0 Connectors Community for Oracle Linux 8 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_mysql }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_x86_64_MySQL80_community"
    organization: "{{ foreman_organization_ol8_mysql }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 8.0 for Oracle Linux 8 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_mysql }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol8_x86_64_MySQL80_tools_community"
    organization: "{{ foreman_organization_ol8_mysql }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}MySQL 8.0 Tools Community for Oracle Linux 8 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol8_mysql }}"

