---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7 | bool }}"


foreman_products_defaults_ol7_olcne: &foreman_products_defaults_ol7_olcne
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_olcne }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_olcne }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_olcne | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_olcne }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_olcne | bool }}"


foreman_products_ol7_olcne:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      ### Oracle Linux Cloud Native Environment (x86_64) | ol7_x86_64_olcne ###
      - name: Oracle Linux Cloud Native Environment (x86_64)
        description: Latest packages for components of the Oracle Linux Cloud Native environment (x86_64)
        label: ol7_x86_64_olcne
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne/x86_64/"
        <<: *foreman_products_defaults_ol7_olcne
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.1 (x86_64) | ol7_x86_64_olcne11 ###
      - name: Oracle Linux Cloud Native Environment 1.1 (x86_64)
        description: Packages for components of the 1.1 release of Oracle Linux Cloud Native environment (x86_64)
        label: ol7_x86_64_olcne11
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne11/x86_64/"
        <<: *foreman_products_defaults_ol7_olcne
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.2 - Oracle LInux 7 (x86_64) | ol7_x86_64_olcne12 ###
      - name: Oracle Linux Cloud Native Environment 1.2 - Oracle LInux 7 (x86_64)
        description: Packages for components of the 1.2 release of Oracle Linux Cloud Native environment for Oracle Linux 7 (x86_64)
        label: ol7_x86_64_olcne12
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne12/x86_64/"
        <<: *foreman_products_defaults_ol7_olcne
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.3 - Oracle LInux 7 (x86_64) | ol7_x86_64_olcne13 ###
      - name: Oracle Linux Cloud Native Environment 1.3 - Oracle LInux 7 (x86_64)
        description: Packages for components of the 1.3 release of Oracle Linux Cloud Native environment for Oracle Linux 7 (x86_64)
        label: ol7_x86_64_olcne13
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne13/x86_64/"
        <<: *foreman_products_defaults_ol7_olcne
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.4 - Oracle LInux 7 (x86_64) | ol7_x86_64_olcne14 ###
      - name: Oracle Linux Cloud Native Environment 1.4 - Oracle LInux 7 (x86_64)
        description: Packages for components of the 1.4 release of Oracle Linux Cloud Native environment for Oracle Linux 7 (x86_64)
        label: ol7_x86_64_olcne14
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne14/x86_64/"
        <<: *foreman_products_defaults_ol7_olcne
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.5 - Oracle LInux 7 (x86_64) | ol7_x86_64_olcne15 ###
      - name: Oracle Linux Cloud Native Environment 1.5 - Oracle LInux 7 (x86_64)
        description: Packages for components of the 1.5 release of Oracle Linux Cloud Native environment for Oracle Linux 7 (x86_64)
        label: ol7_x86_64_olcne15
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne15/x86_64/"
        <<: *foreman_products_defaults_ol7_olcne
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Developer Preview for Oracle Linux Cloud Native Environment (x86_64) | ol7_x86_64_developer_olcne ###
      - name: Developer Preview for Oracle Linux Cloud Native Environment (x86_64)
        description: Developer preview packages for components of the Oracle Linux Cloud Native environment (x86_64)
        label: ol7_x86_64_developer_olcne
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/developer/olcne/x86_64/"
        <<: *foreman_products_defaults_ol7_olcne
        organization: "{{ foreman_organization_ol7_olcne }}"


foreman_content_views_ol7_olcne:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_olcne"
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Cloud Native Environment (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_olcne11"
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Cloud Native Environment 1.1 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_olcne12"
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Cloud Native Environment 1.2 - Oracle LInux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_olcne13"
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Cloud Native Environment 1.3 - Oracle LInux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_olcne14"
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Cloud Native Environment 1.4 - Oracle LInux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_olcne15"
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle Linux Cloud Native Environment 1.5 - Oracle LInux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_olcne }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_x86_64_developer_olcne"
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Developer Preview for Oracle Linux Cloud Native Environment (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_olcne }}"

