---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oracle"
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln | bool }}"
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"


foreman_products_defaults_ol7_uln_cloud: &foreman_products_defaults_ol7_uln_cloud
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln_cloud }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln_cloud }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln_cloud | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln_cloud }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln_cloud | bool }}"


foreman_products_ol7_uln_cloud_openstack20:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack20 }}"
    repositories:
      ### Oracle OpenStack 2.0 (x86_64) | ol7_x86_64_openstack20 ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 2.0 (x86_64)"
        description: Latest for Oracle OpenStack version 2.0 .
        label: "{{ foreman_repo_label_prefix | default('') }}ol7_uln_x86_64_openstack20"
        <<: *foreman_products_defaults_ol7_uln_cloud
        url: uln://ol7_x86_64_openstack20
        organization: "{{ foreman_organization_ol7_uln_cloud_openstack20 }}"

foreman_products_ol7_uln_cloud_openstack21:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack21 }}"
    repositories:
      ### Oracle OpenStack 2.1 for Oracle Linux 7 (x86_64) | ol7_x86_64_openstack21 ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 2.1 for Oracle Linux 7 (x86_64)"
        description: Latest for Oracle OpenStack version 2.1 for Oracle Linux 7 (x86_64) .
        label: "{{ foreman_repo_label_prefix | default('') }}ol7_uln_x86_64_openstack21"
        <<: *foreman_products_defaults_ol7_uln_cloud
        url: uln://ol7_x86_64_openstack21
        organization: "{{ foreman_organization_ol7_uln_cloud_openstack21 }}"

foreman_products_ol7_uln_cloud_openstack30:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack30 }}"
    repositories:
      ### Oracle OpenStack 3.0 for Oracle Linux 7 (x86_64) | ol7_x86_64_openstack30 ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 3.0 for Oracle Linux 7 (x86_64)"
        description: Latest for Oracle OpenStack version 3.0 .
        label: "{{ foreman_repo_label_prefix | default('') }}ol7_uln_x86_64_openstack30"
        <<: *foreman_products_defaults_ol7_uln_cloud
        url: uln://ol7_x86_64_openstack30
        organization: "{{ foreman_organization_ol7_uln_cloud_openstack30 }}"
      ### Extra development packages for Oracle OpenStack 3.0 on Oracle Linux 7 (x86_64) | ol7_x86_64_openstack_extras ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Extra development packages for Oracle OpenStack 3.0 on Oracle Linux 7 (x86_64)"
        description: Latest Extra development packages for Oracle OpenStack version 3.0
        label: "{{ foreman_repo_label_prefix | default('') }}ol7_uln_x86_64_openstack_extras"
        <<: *foreman_products_defaults_ol7_uln_cloud
        url: uln://ol7_x86_64_openstack_extras
        organization: "{{ foreman_organization_ol7_uln_cloud_openstack30 }}"

foreman_products_ol7_uln_cloud_openstack40:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack40 }}"
    repositories:
      ### Oracle OpenStack 4.0 for Oracle Linux 7 (x86_64) | ol7_x86_64_openstack40 ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 4.0 for Oracle Linux 7 (x86_64)"
        description: Latest Packages for Oracle OpenStack version 4.0 .
        label: "{{ foreman_repo_label_prefix | default('') }}ol7_uln_x86_64_openstack40"
        <<: *foreman_products_defaults_ol7_uln_cloud
        url: uln://ol7_x86_64_openstack40
        organization: "{{ foreman_organization_ol7_uln_cloud_openstack40 }}"
      ### Extra development packages for Oracle OpenStack 4.0 on Oracle Linux 7 (x86_64) | ol7_x86_64_openstack40_extras ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Extra development packages for Oracle OpenStack 4.0 on Oracle Linux 7 (x86_64)"
        description: Latest Extra development packages for Oracle OpenStack version 4.0
        label: "{{ foreman_repo_label_prefix | default('') }}ol7_uln_x86_64_openstack40_extras"
        <<: *foreman_products_defaults_ol7_uln_cloud
        url: uln://ol7_x86_64_openstack40_extras
        organization: "{{ foreman_organization_ol7_uln_cloud_openstack40 }}"

foreman_products_ol7_uln_cloud_openstack50:
  - name: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    label: "{{ foreman_product_label_prefix | default('') }}OL"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack50 }}"
    repositories:
      ### Oracle OpenStack 5.0 for Oracle Linux 7 (x86_64) | ol7_x86_64_openstack50 ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 5.0 for Oracle Linux 7 (x86_64)"
        description: Latest Packages for Oracle OpenStack version 5.0 .
        label: "{{ foreman_repo_label_prefix | default('') }}ol7_uln_x86_64_openstack50"
        <<: *foreman_products_defaults_ol7_uln_cloud
        url: uln://ol7_x86_64_openstack50
        organization: "{{ foreman_organization_ol7_uln_cloud_openstack50 }}"
      ### Extra development packages for Oracle OpenStack 5.0 on Oracle Linux 7 (x86_64) | ol7_x86_64_openstack50_extras ###
      - name: "{{ foreman_repo_name_prefix | default('') }}Extra development packages for Oracle OpenStack 5.0 on Oracle Linux 7 (x86_64)"
        description: Latest Extra development packages for Oracle OpenStack version 5.0
        label: "{{ foreman_repo_label_prefix | default('') }}ol7_uln_x86_64_openstack50_extras"
        <<: *foreman_products_defaults_ol7_uln_cloud
        url: uln://ol7_x86_64_openstack50_extras
        organization: "{{ foreman_organization_ol7_uln_cloud_openstack50 }}"

foreman_products_ol7_uln_cloud: "{{ [] |
  union( foreman_products_ol7_uln_cloud_openstack20 | default([]) if foreman_enable_ol7_uln_cloud_openstack20 else [] ) |
  union( foreman_products_ol7_uln_cloud_openstack21 | default([]) if foreman_enable_ol7_uln_cloud_openstack21 else [] ) |
  union( foreman_products_ol7_uln_cloud_openstack30 | default([]) if foreman_enable_ol7_uln_cloud_openstack30 else [] ) |
  union( foreman_products_ol7_uln_cloud_openstack40 | default([]) if foreman_enable_ol7_uln_cloud_openstack40 else [] ) |
  union( foreman_products_ol7_uln_cloud_openstack50 | default([]) if foreman_enable_ol7_uln_cloud_openstack50 else [] )
  }}"


foreman_content_views_ol7_uln_cloud_openstack20:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_openstack20"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack20 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 2.0 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_cloud_openstack20 }}"

foreman_content_views_ol7_uln_cloud_openstack21:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_openstack21"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack21 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 2.1 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_cloud_openstack21 }}"

foreman_content_views_ol7_uln_cloud_openstack30:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_openstack30"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack30 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 3.0 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_cloud_openstack30 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_openstack_extras"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack30 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Extra development packages for Oracle OpenStack 3.0 on Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_cloud_openstack30 }}"

foreman_content_views_ol7_uln_cloud_openstack40:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_openstack40"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack40 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 4.0 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_cloud_openstack40 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_openstack40_extras"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack40 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Extra development packages for Oracle OpenStack 4.0 on Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_cloud_openstack40 }}"

foreman_content_views_ol7_uln_cloud_openstack50:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_openstack50"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack50 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Oracle OpenStack 5.0 for Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_cloud_openstack50 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ol7_uln_x86_64_openstack50_extras"
    organization: "{{ foreman_organization_ol7_uln_cloud_openstack50 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Extra development packages for Oracle OpenStack 5.0 on Oracle Linux 7 (x86_64)"
        product: "{{ foreman_product_name_prefix | default('') }}Oracle Linux"
    allow_promote: "{{ foreman_cv_allow_promote_ol7_uln_cloud_openstack50 }}"

foreman_content_views_ol7_uln_cloud: "{{ [] |
  union( foreman_content_views_ol7_uln_cloud_openstack20 | default([]) if foreman_enable_ol7_uln_cloud_openstack20 else [] ) |
  union( foreman_content_views_ol7_uln_cloud_openstack21 | default([]) if foreman_enable_ol7_uln_cloud_openstack21 else [] ) |
  union( foreman_content_views_ol7_uln_cloud_openstack30 | default([]) if foreman_enable_ol7_uln_cloud_openstack30 else [] ) |
  union( foreman_content_views_ol7_uln_cloud_openstack40 | default([]) if foreman_enable_ol7_uln_cloud_openstack40 else [] ) |
  union( foreman_content_views_ol7_uln_cloud_openstack50 | default([]) if foreman_enable_ol7_uln_cloud_openstack50 else [] )
  }}"

